apiVersion: v1
kind: Secret
metadata:
  name: bold-azure-secret
  namespace: bold-services1
type: Opaque
data:
  azurestorageaccountname: dGVycmFmb3Jtc3RvcmFnZWF6dXJl
  azurestorageaccountkey: OGZzVldrOE1xVHVOZHZSb3VYdzhHakJ2T2lUMDI2NVBJTTFyVFhzRjZpVGw2dkczTVF3VEE3U0tTNElnZnF2NmxyS01YQUdEb01DUkpnUGRpZTNPY3c9PQ==
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: bold-fileserver1
 namespace: bold-services1
spec:
 capacity:
   storage: 3Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 storageClassName: azurefile
 azureFile:
   secretName: bold-azure-secret
   shareName: sharename1
   readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: bold-fileserver-claim1
 namespace: bold-services1
spec:
 accessModes:
 - ReadWriteMany
 storageClassName: azurefile
 volumeName: bold-fileserver1
 resources:
   requests:
     storage: 3Gi
